"""SVG preview generation tests (golden + real-collection invariants)."""

from __future__ import annotations

import json
import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from icons import (  # noqa: E402
    COLLECTIONS,
    PREVIEWS_REL,
    SVG_NS,
    CollectionSpec,
    IconValidationError,
    PreviewJob,
    build_manifest,
    cleanup_stale_previews,
    filename_for,
    prepare_artifacts,
    render_preview_svg,
    write_if_changed,
    write_previews,
)

GOLDEN = Path(__file__).resolve().parent / "golden"


def _write_pack(
    path: Path,
    *,
    prefix: str,
    icons: dict,
    width: int | None = 48,
    height: int | None = 48,
    aliases: dict | None = None,
) -> None:
    data: dict = {
        "prefix": prefix,
        "info": {
            "name": prefix.upper(),
            "author": {"name": "Test", "url": "https://example.com"},
            "license": {"title": "CC0", "spdx": "CC0-1.0", "url": "https://example.com/license"},
        },
        "lastModified": 1700000000,
        "icons": icons,
    }
    if width is not None:
        data["width"] = width
    if height is not None:
        data["height"] = height
    if aliases is not None:
        data["aliases"] = aliases
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8", newline="\n")


def _fixture_root(tmp_path: Path) -> tuple[Path, tuple[CollectionSpec, ...]]:
    """Eight-icon fixture covering full dims, defaults, offsets, sanitised name, alias."""
    pack = tmp_path / "docs" / "assets" / "mermaid-icons" / "demo.json"
    _write_pack(
        pack,
        prefix="demo",
        width=48,
        height=48,
        icons={
            "full-dims": {
                "body": '<path d="M0 0h16v16H0z" fill="#111"/>',
                "width": 16,
                "height": 16,
            },
            "collection-default": {
                "body": '<circle cx="24" cy="24" r="20" fill="#222"/>',
            },
            "with-offsets": {
                "body": '<rect width="100" height="40" fill="#333"/>',
                "width": 100,
                "height": 40,
                "left": 0.1,
                "top": 31.4,
            },
            "weird-&-key": {
                "body": '<path d="M1 1h8v8H1z" fill="#444"/>',
            },
            "parent-icon": {
                "body": '<ellipse cx="8" cy="8" rx="8" ry="8" fill="#555"/>',
                "width": 16,
                "height": 16,
            },
            "hidden-one": {
                "body": '<path d="M0 0h4v4H0z"/>',
                "hidden": True,
            },
            "mixed-dims": {
                "body": '<path d="M0 0h32v48H0z"/>',
                "width": 32,
            },
            "float-left": {
                "body": '<path d="M0 0h10v10H0z"/>',
                "width": 10,
                "height": 10,
                "left": 0.1,
            },
        },
        aliases={"alias-of-parent": {"parent": "parent-icon"}},
    )
    specs = (CollectionSpec("demo", "docs/assets/mermaid-icons/demo.json"),)
    return tmp_path, specs


# --- render / safety / well-formedness ----------------------------------------


def test_render_preview_svg_shape() -> None:
    job = PreviewJob(
        rel_path="reference/icons/previews/demo/full-dims.svg",
        slug="demo:full-dims",
        source_json="docs/assets/mermaid-icons/demo.json",
        width=16,
        height=16,
        left=0,
        top=0,
        body='<path d="M0 0h16v16H0z"/>',
    )
    text = render_preview_svg(job)
    assert text.startswith(
        "<!-- Generated by scripts/icons.py from docs/assets/mermaid-icons/demo.json "
        "(demo:full-dims). Do not edit. -->\n"
    )
    assert 'xmlns="http://www.w3.org/2000/svg"' in text
    assert 'xmlns:xlink="http://www.w3.org/1999/xlink"' in text
    assert 'width="16" height="16" viewBox="0 0 16 16"' in text
    assert text.endswith("</svg>\n")
    assert "\r" not in text


def test_script_body_rejected(tmp_path: Path) -> None:
    pack = tmp_path / "docs" / "assets" / "mermaid-icons" / "demo.json"
    _write_pack(
        pack,
        prefix="demo",
        icons={"evil": {"body": '<script>alert(1)</script><path d="M0 0h1v1H0z"/>'}},
    )
    with pytest.raises(IconValidationError) as exc:
        prepare_artifacts(
            root=tmp_path,
            collections=(CollectionSpec("demo", "docs/assets/mermaid-icons/demo.json"),),
        )
    assert any("safety scan" in e for e in exc.value.errors)


@pytest.mark.parametrize(
    "body",
    [
        '<foreignObject width="1" height="1"></foreignObject>',
        "<!DOCTYPE svg>",
        '<!ENTITY x "y"><path/>',
        '<rect width="1" height="1" onclick="x()"/>',
        '<path onload = "x()" d="M0 0"/>',
    ],
)
def test_unsafe_bodies_rejected(tmp_path: Path, body: str) -> None:
    pack = tmp_path / "docs" / "assets" / "mermaid-icons" / "demo.json"
    _write_pack(pack, prefix="demo", icons={"bad": {"body": body}})
    with pytest.raises(IconValidationError) as exc:
        prepare_artifacts(
            root=tmp_path,
            collections=(CollectionSpec("demo", "docs/assets/mermaid-icons/demo.json"),),
        )
    assert any("safety scan" in e for e in exc.value.errors)


def test_malformed_body_rejected(tmp_path: Path) -> None:
    pack = tmp_path / "docs" / "assets" / "mermaid-icons" / "demo.json"
    _write_pack(
        pack,
        prefix="demo",
        icons={"broken": {"body": "<path d='M0 0'"}},  # unclosed
    )
    with pytest.raises(IconValidationError) as exc:
        prepare_artifacts(
            root=tmp_path,
            collections=(CollectionSpec("demo", "docs/assets/mermaid-icons/demo.json"),),
        )
    assert any("well-formed" in e for e in exc.value.errors)


# --- golden SVGs --------------------------------------------------------------


@pytest.mark.parametrize(
    ("key", "golden_name"),
    [
        ("full-dims", "full-dims.svg"),
        ("collection-default", "collection-default.svg"),
        ("with-offsets", "offsets.svg"),
        ("weird-&-key", "sanitized-filename.svg"),
    ],
)
def test_golden_svgs(tmp_path: Path, key: str, golden_name: str) -> None:
    root, specs = _fixture_root(tmp_path)
    _, jobs = prepare_artifacts(root=root, collections=specs)
    job = next(j for j in jobs if j.slug == f"demo:{key}")
    assert job.rel_path.endswith(filename_for(key))
    rendered = render_preview_svg(job)
    expected = (GOLDEN / golden_name).read_text(encoding="utf-8").replace("\r\n", "\n")
    assert rendered == expected


# --- write / stale cleanup / no-op --------------------------------------------


def test_stale_preview_removed(tmp_path: Path) -> None:
    root, specs = _fixture_root(tmp_path)
    _, jobs = prepare_artifacts(root=root, collections=specs)
    write_previews(jobs, root=root)

    stale = root / PREVIEWS_REL / "demo" / "zzz-not-an-icon.svg"
    stale.write_text("<svg xmlns='http://www.w3.org/2000/svg'/>\n", encoding="utf-8")
    removed = cleanup_stale_previews(jobs, root=root)
    assert not stale.exists()
    assert any(r.endswith("zzz-not-an-icon.svg") for r in removed)


def test_unchanged_preview_not_rewritten(tmp_path: Path) -> None:
    root, specs = _fixture_root(tmp_path)
    _, jobs = prepare_artifacts(root=root, collections=specs)
    written1, unchanged1 = write_previews(jobs, root=root)
    assert written1 == len(jobs) and unchanged1 == 0

    path = root / jobs[0].rel_path
    mtime_before = path.stat().st_mtime_ns
    time.sleep(0.02)
    written2, unchanged2 = write_previews(jobs, root=root)
    assert written2 == 0 and unchanged2 == len(jobs)
    assert path.stat().st_mtime_ns == mtime_before


def test_write_if_changed_skips_identical(tmp_path: Path) -> None:
    path = tmp_path / "a.svg"
    assert write_if_changed(path, "hello\n") is True
    assert write_if_changed(path, "hello\n") is False
    assert write_if_changed(path, "hello\r\n") is False  # normalised compare
    assert write_if_changed(path, "other\n") is True


def test_previews_false_emits_no_jobs(tmp_path: Path) -> None:
    pack = tmp_path / "docs" / "assets" / "mermaid-icons" / "demo.json"
    _write_pack(pack, prefix="demo", icons={"a": {"body": "<path/>"}})
    _, jobs = prepare_artifacts(
        root=tmp_path,
        collections=(
            CollectionSpec("demo", "docs/assets/mermaid-icons/demo.json", previews=False),
        ),
    )
    assert jobs == []


def test_empty_collection_dir_removed_after_cleanup(tmp_path: Path) -> None:
    root, specs = _fixture_root(tmp_path)
    _, jobs = prepare_artifacts(root=root, collections=specs)
    write_previews(jobs, root=root)

    orphan_dir = root / PREVIEWS_REL / "gone"
    orphan_dir.mkdir(parents=True)
    (orphan_dir / "orphan.svg").write_text("<svg xmlns='http://www.w3.org/2000/svg'/>\n")
    cleanup_stale_previews(jobs, root=root)
    assert not orphan_dir.exists()


# --- real collections (committed artifacts) -----------------------------------


@pytest.fixture(scope="module")
def real_manifest() -> dict:
    return build_manifest(root=ROOT, collections=COLLECTIONS)


def test_real_manifest_icon_count(real_manifest: dict) -> None:
    # 867 aws icons + 2091 logos icons + 7 logos aliases
    assert len(real_manifest["icons"]) == 867 + 2091 + 7
    by_coll = {c["id"]: c["icon_count"] for c in real_manifest["collections"]}
    assert by_coll["aws"] == 867
    assert by_coll["logos"] == 2098


def test_real_preview_files_exist_and_parse(real_manifest: dict) -> None:
    previews_root = ROOT / PREVIEWS_REL
    assert previews_root.is_dir()

    slugs = set()
    preview_paths = set()
    for entry in real_manifest["icons"]:
        slug = entry["slug"]
        preview = entry["preview"]
        assert slug not in slugs
        assert preview not in preview_paths
        slugs.add(slug)
        preview_paths.add(preview)

        path = ROOT / preview
        assert path.is_file(), f"MISSING {preview}"
        text = path.read_text(encoding="utf-8")
        assert "\r" not in text
        assert text.startswith("<!-- Generated by scripts/icons.py from ")
        xml_payload = text.split("\n", 1)[1]
        root_el = ET.fromstring(xml_payload)
        assert root_el.tag == f"{{{SVG_NS}}}svg"

    # no extras on disk
    on_disk = {
        p.relative_to(ROOT).as_posix()
        for p in previews_root.rglob("*.svg")
        if p.is_file()
    }
    assert on_disk == preview_paths


def test_real_preview_paths_posix(real_manifest: dict) -> None:
    for entry in real_manifest["icons"]:
        preview = entry["preview"]
        assert "\\" not in preview
        assert not preview.startswith("/")
        assert preview.startswith("reference/icons/previews/")
